# Generated by Django 3.0.3 on 2020-02-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/report')),
            ],
        ),
    ]
