# Generated by Django 3.0.3 on 2020-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Report',
        ),
    ]
