# Generated by Django 3.0.3 on 2020-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0002_auto_20200228_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_basic_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='permission',
            field=models.CharField(choices=[('FOLFER_TO_USER', 'Folder to User'), ('FOLDER_TO_GROUP', 'Folder to Group'), ('GROUP_TO_USER', 'Group to Folder')], max_length=100),
        ),
    ]
