# Generated by Django 3.0.3 on 2020-03-02 21:05

from django.db import migrations, models
import multiselectfield.db.fields
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0003_auto_20200228_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(help_text='Formats accepted: CSV', upload_to='files/report', validators=[upload_validator.FileTypeValidator(allowed_types=['text/csv'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='permission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOLFER_TO_USER', 'Folder to User'), ('FOLDER_TO_GROUP', 'Folder to Group'), ('GROUP_TO_USER', 'Group to Folder')], max_length=44),
        ),
    ]
