# Generated by Django 3.0.3 on 2020-03-02 22:03

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0004_auto_20200302_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(help_text='Formats accepted: CSV', upload_to='files/report', validators=[upload_validator.FileTypeValidator(allowed_types=['text/csv', 'application/vnd.ms-excel', 'text/plain', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])]),
        ),
    ]
