# Generated by Django 3.0.3 on 2020-03-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0005_auto_20200302_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='permission',
        ),
    ]
