# Generated by Django 3.0.3 on 2020-03-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadform', '0006_remove_report_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pivot_perm_folder_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='pivot_perm_folder_to_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pivot_perm_group_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
